import withSerwistInit from "@serwist/next";
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Dev runs on Turbopack (Next 16's default). Serwist builds the service
  // worker via a webpack plugin, so `withSerwistInit` always adds a `webpack`
  // key to this config — which Turbopack rejects unless an (even empty)
  // `turbopack` config is also present. The SW is disabled in dev anyway
  // (see below); it's generated by `next build --webpack` (see package.json).
  turbopack: {},
  images: {
    // Cloudinary signed URLs and Clerk avatars are served from these hosts.
    remotePatterns: [
      { protocol: "https", hostname: "res.cloudinary.com" },
      { protocol: "https", hostname: "img.clerk.com" },
    ],
  },
};

const withSerwist = withSerwistInit({
  swSrc: "app/sw.ts",
  swDest: "public/sw.js",
  // Service worker only runs in production builds; avoids caching headaches in dev.
  disable: process.env.NODE_ENV === "development",
});

export default withSerwist(nextConfig);
